
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */
/* do not edit */ import { RundownItemType } from "./RundownItemType";
/* do not edit */
/* do not edit */
/* do not edit */ export class RundownItem {
/* do not edit */     
/* do not edit */     public id: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public index: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public name: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public type: RundownItemType;
/* do not edit */ }
/* do not edit */