
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */
/* do not edit */ import { RundownItem } from "./RundownItem";
/* do not edit */
/* do not edit */
/* do not edit */ export class RundownItemType {
/* do not edit */     
/* do not edit */     public id: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public name: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public description: string;
/* do not edit */     
/* do not edit */     
/* do not edit */     public color: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public rundownItems: RundownItemType[];
/* do not edit */
/* do not edit */ }
/* do not edit */